---
name: Question
description: Ask a question.
title: "[QUESTION] Title"
labels: Question
body:
- type: markdown
  attributes:
    value: |
      If the question is related to AMD hardware, please mention [Nathan Fontenot](https://github.com/nfont).

- type: textarea
  attributes:
    label: Question
    description: >-
      Ask a question.
  validations:
    required: true

- type: textarea
  attributes:
    label: Environment
    description: |
      Please describe your environment.
    value: |
      Include relevant details about the environment you're working in.
      OS:
      What type of controller and disk the question is directed to:
  validations:
    required: false
...
